# Generated by Django 3.2.13 on 2022-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_priority_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1996-05-25'),
            preserve_default=False,
        ),
    ]
